### ISSUE TITLE
minibar 0.4.0 not available via pypi?

### ISSUE THREAD

**Issue by makefu** [canassa/minibar#3]
hi, currently i am facing the issue that i cannot get the latest version of minibar via pip:

     ~> pip install  minibar==0.4.0
    Collecting minibar==0.4.0
      Could not find a version that satisfies the requirement minibar==0.4.0 (from versions: 0.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1)
      No distributions matching the version for minibar==0.4.0

`pip install  minibar==0.3.1`  is working.

Regards,

makefu

**Comment by canassa** [comment]
I re-uploaded it. Could you try again?

**Comment by makefu** [comment]
everything is working, yay :D
thanks!
